project:
  type: website
  output-dir: docs  # Pasta de saída para GitHub Pages

website:
  title: "BIODESTOCA"
  navbar:
    background: "#6D5D54"  # Marrom escuro terroso
    primary: "#A9927D"     # Marrom claro (hover e destaque)
    left:
      - text: ""
        href: index.qmd
      - text: "Apresentação"
        href: introducao.qmd
      - text: "Estatísticas"
        href: melhoresprodutores.qmd
      - text: "Visualização"
        href: resultados.qmd
      - text: "Conclusão"
        href: conclusao.qmd
    right:
      - text: "GitHub"
        href: "https://github.com/vitxriab7"
      - icon: search

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    include-after-body:
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css">
    include-in-header:
      - text: |
          <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600&family=Playfair+Display:wght@700&display=swap" rel="stylesheet">

